name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: tests (local)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Generate parser
        run: tree-sitter generate --log --report-states-for-rule -
      - name: Compile parser
        run: tree-sitter build
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-parser-cmd: tree-sitter test --stat all
  test:
    name: tests (examples)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Set up real-life examples
        uses: actions/checkout@v4
