name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: test (${{ matrix.language }})
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        language: [rust, node, python, go, swift]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Generate parser
        run: tree-sitter generate
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{ matrix.language == 'rust' }}
          test-node: ${{ matrix.language == 'node' }}
          test-python: ${{ matrix.language == 'python' }}
          test-go: ${{ matrix.language == 'go' }}
          test-swift: ${{ matrix.language == 'swift' }}
