on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      directory:
        required: true
        type: string
      checkout-directories:
        required: true
        type: string

jobs:
  fast-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ inputs.repository }}
        run: |-
          git clone --single-branch --depth=1 --filter=blob:none --no-checkout https://github.com/${{inputs.repository}} ${{inputs.directory}}
          cd ${{inputs.directory}}
          git sparse-checkout init --cone
          git sparse-checkout set ${{inputs.checkout-directories}}
          git checkout
